version: "3.5"
services:
  app:
    image: 192.168.0.2:5050/dedyms/euterpe:latest
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - /media/WD/Music:/musics
      - data:/home/debian/.euterpe
    ports:
       - 2000:443
    configs:
       - source: config.json
         target: /home/debian/.euterpe/config.json
    deploy:
      placement:
        constraints:
          - node.hostname == homelab
    networks:
      - euterpe

networks:
  euterpe:
    name: euterpe

volumes:
  data:

configs:
  config.json:
    file: config.json