version: "3.5"
services:
  documentserver:
    image: onlyoffice/documentserver:7.0
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
      - USE_UNAUTHORIZED_STORAGE=true
      #- SSL_VERIFY_CLIENT=false
      #- SSL_CERTIFICATE_PATH=/etc/ssl/certs/ssl-cert-snakeoil.pem
      #- SSL_KEY_PATH=/etc/ssl/private/ssl-cert-snakeoil.key
    #ports:
    #  - 5080:80
    volumes:
      - ds_logs:/var/log/onlyoffice
      - ds_data:/var/www/onlyoffice/Data
    networks:
      - onlyoffice
    deploy:
      placement:
        constraints: [node.hostname == homelab]

  apache:
    image: 192.168.0.2:5050/dedyms/apache:fcgid
    configs:
      - source: apache.conf
        target: /etc/apache2/sites-available/000-default-ssl.conf
    networks:
      - onlyoffice
    deploy:
      placement:
        constraints: [ node.hostname == homelab ]
    ports:
      - 5080:443

volumes:
  ds_logs:
  ds_data:

networks:
  onlyoffice:
    name: onlyoffice

configs:
  apache.conf:
    file: ./apache.conf
